apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: employee-be-hpa
  namespace: backend
  labels:
    app: employee-be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-be
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
