apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adminer
  namespace: backend
spec:
  serviceName: adminer
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:standalone
          ports:
            - containerPort: 8080
              name: adminer
