apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-be
  namespace: backend
  labels:
    app: employee-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-be
  template:
    metadata:
      labels:
        app: employee-be
    spec:
      containers:
        - name: employee-be
          image: devops/employee-be:1.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: instance-port
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: employee-be-config
          livenessProbe:
            httpGet:
              path: /api/health
              port: instance-port
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: instance-port
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /api/health
              port: instance-port
            initialDelaySeconds: 30
            periodSeconds: 10
