apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-fe
  namespace: frontend
  labels:
    app: employee-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-fe
  template:
    metadata:
      labels:
        app: employee-fe
    spec:
      containers:
        - name: employee-fe
          image: devops/employee-fe:1.0.17
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: employee-fe-config
