apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-fe
  namespace: frontend
  labels:
    app: employee-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-fe
  template:
    metadata:
      labels:
        app: employee-fe
    spec:
      containers:
        - name: employee-fe
          image: devops/employee-fe:1.0.18
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: employee-fe-config
          ports:
            - containerPort: 80
              name: web-port
          readinessProbe:
            httpGet:
              path: /api/health
              port: web-port
            initialDelaySeconds: 20
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /api/health
              port: web-port
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: web-port
            initialDelaySeconds: 3
            periodSeconds: 3
