apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-be
  namespace: backend
  labels:
    app: employee-be
spec:
  selector:
    matchLabels:
      app: employee-be
  template:
    metadata:
      labels:
        app: employee-be
    spec:
      containers:
        - name: employee-be
          image: devops/employee-be:1.0.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: instance-port
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: employee-be-config
          livenessProbe:
            httpGet:
              path: /api/health
              port: instance-port
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: instance-port
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/health
              port: instance-port
            initialDelaySeconds: 20
            periodSeconds: 10
